Add missing pcl_macros import
Fixes compile issue which looks like

elevation_mapping/elevation_mapping/include/elevation_mapping/PointXYZRGBConfidenceRatio.hpp:28:3: error: ‘PCL_MAKE_ALIGNED_OPERATOR_NEW’ does not name a type; did you mean ‘EIGEN_MAKE_ALIGNED_OPERATOR_NEW’?
   PCL_MAKE_ALIGNED_OPERATOR_NEW
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   EIGEN_MAKE_ALIGNED_OPERATOR_NEW

Fixes issue #151